### ISSUE TITLE
Blazor server or blazor SSR example?

### ISSUE THREAD

**Issue by barelabs** [Eptagone/Vite.AspNetCore#100]
Thanks for this great library.  In your readme, it says there is an example with Blazor server, but cannot find the example?  Am I missing the example somewhere?

If there isn't an example, how do I add the script tags without tag helpers?  From what I understand, tag helpers are not supported in Blazor components, and any of the .NET 8 templates do not have an _ViewImports.cshtml file where normally the tag helpers are added.  

I tried adding the tag helpers to the _Imports.razor file, but tag helpers are not supported there.  It sounds like a lot is going on under the hood with the tag helpers, so would rather not put in hard-coded links to the Vite entry files.  Thank you for any help with a Blazor example and how to add these scripts.

**Comment by Eptagone** [comment]
Ups. I think I deleted it by accident.
Let me see.

**Comment by Eptagone** [comment]
Hi. I added the example again. [Here](https://github.com/Eptagone/Vite.AspNetCore/tree/main/examples/net/ViteNET.BlazorServer)
