### ISSUE TITLE
AutoRunning the dev server causes a shell script to appear in the root directory.

### ISSUE THREAD

**Issue by dagstuan** [Eptagone/Vite.AspNetCore#112]
**Describe the bug**
Both in the examples and my own code, every time I start the application a new shell script shows up in the root directory of my app. Such as `326cca0f61ce49b7909cb09623b72153.sh`. If I manually start the vite dev server in advance, no script shows up.

<img width="622" alt="image" src="https://github.com/Eptagone/Vite.AspNetCore/assets/397559/4d279d4f-92cf-4b86-b600-a0f4c1721800">

**To Reproduce**
1. Clone this repository. Go to `/examples/libraries/ViteNET.React`
2. Run `dotnet run`
3. Open the webpage to start the vite dev server.
4. See the new shell script in the root directory

**Expected behavior**
No shell script to show up

**Screenshots**
<img width="374" alt="image" src="https://github.com/Eptagone/Vite.AspNetCore/assets/397559/34b47d6e-3820-4f0d-bb71-2d5b2c36f6e9">

**Device (please complete the following information):**
- Mac OS Sonoma 14.2.1

**Comment by Eptagone** [comment]
Hello `@dagstuan`.
I just changed the script directory in 0f9bf04f733e8fc3103ad9929d2e87d330b55a72. Branch [dev](https://github.com/Eptagone/Vite.AspNetCore/tree/dev).

I think it should be enough but if you or someone with MacOS could help me by verifying it locally before publishing it, I would greatly appreciate it.

**Comment by dagstuan** [comment]
Hello again, the changes makes the script show up in `bin/Debug/net8.0` instead, which is a definite improvement. However, there is still the issue of the script being recreated every time I restart the app, so over time the `bin/debug/net8.0`-folder will be swarmed with shell scripts. Is there any way of re-using the script if it already exists? Maybe by creating a file name based on the hash of the contents instead of a random name every time?

<img width="369" alt="image" src="https://github.com/Eptagone/Vite.AspNetCore/assets/397559/6514a9ed-8a67-4843-adb5-cab7486eca18">

**Comment by Eptagone** [comment]
Hi again @dagstuan.
I just changed the script name to be a constant value in https://github.com/Eptagone/Vite.AspNetCore/commit/4136a183b9482d36ed76aa8a4c73263b9af398a9. Branch [dev](https://github.com/Eptagone/Vite.AspNetCore/tree/dev).

Please confirm to me if it works correctly or if any more changes need to be made.

**Comment by dagstuan** [comment]
The changes work great now! Thanks!

**Comment by matteocontrini** [comment]
@Eptagone could you release this? 🙏 

It should be the same issue as in #75

**Comment by Eptagone** [comment]
Done with f87721758e3871644f13570db429f26acf75cbb4
