### ISSUE TITLE
The source files of vite override the routes defined in ASP

### ISSUE THREAD

**Issue by TanguyPa** [Eptagone/Vite.AspNetCore#12]
My ASP application runs on the URL : https://localhost:7243/
The middleware exposes the client source files (vite) on this same url when used with a vite dev server.

For example: If I have a file named main.js or main.ts in my src folder, and I have an ASP MVC page bind to the "/main" route.
When I access the /main route, from the URL of my ASP server : https://localhost:7243/main
It displays the source code of my main.ts file instead of displaying the view associated to the route.

I don't have this problem if I disable the library and run vite dev server manually.

I tried to disable autorun but it doesn't change anything.

My lib config : 
```json
  "Vite": {
    "WorkingDirectory":  "ClientApp",
    "PackageManager": "pnpm",
    "Server": {
      "AutoRun": false,
      // The port where the Vite Dev Server will be running. The default value is 5173.
      "Port": 5173,
      // If true, the middleware will use HTTPS to connect to the Vite Dev Server. The default value is false.
      "UseHttps": false
    }
```
And my vite.config.ts
```ts
import { defineConfig } from "vite"

export default defineConfig({
   base: '/src/',
   root: './src',
   build: {
        modulePreload: {
            polyfill: true
        },
        assetsDir: '',
        manifest: true,
        outDir: '../../wwwroot/dist/',
        emptyOutDir: true,
        rollupOptions: {
            input: {
                main: 'src/main.ts',
            },
            output: {
                entryFileNames: `[name].js`,
                chunkFileNames: `[name].js`,
                assetFileNames: `[name].[ext]`,
            }         
        },
    },
})
```

**Comment by Eptagone** [comment]
Hi @TanguyPa
I see you entry point name is also main. That's the problem. Entry points in vite dev server are retrieved via `http(s)://localhost:{port}/{entry-point|filename}`

Try to rename your entrypoint to:
```
input: {
    'main.ts': 'src/main.ts',
},
```

Let me know if it worked for you

**Comment by TanguyPa** [comment]
Hi thanks for your reply,

I just tried it but it doesn't solve the problem.
I noticed that if I create any file in my src folder (js/ts/scss), this file is accessible via https://localhost:7243/{fileName} or https://localhost:7243/{fileName}.{ext}, even if the file is not used
For example I just created a test.js file in my src folder and no other file imports or uses this file (the file is not configured as an entry point), however the file is accessible

I thought that the entry point would be accessible only on the port of the vite server (i.e. 5173) and not the port of my ASP server

**Comment by Eptagone** [comment]
Hi. Mmm I see.
Then the other option is to change the order of the middlewares. In your Program.cs or Startup.cs file, move app.UseViteDevMiddleware() to the end, after the others app.Use*()

Let me know if it worked for you. If not, then I'll see what can be done on the library side.

**Comment by TanguyPa** [comment]
Hi,
I tried to add it just before my app.Run() but it does not change anything.

I think it comes from the proxy in the middleware, in my case I can't grasp purpose to have this proxy on my app. Maybe I'm not using the library correctly.
Would it be possible to disable the proxy via a parameter that we would pass to ViteDevMiddleware ?

**Comment by Eptagone** [comment]
To disable the proxy, disable the middleware. Remove the line app.UseViteDevMiddleware(); from your code.

**Comment by Eptagone** [comment]
Hi. I finally found a solution with the commit 95c512cc236833cde36aedda5ebee7922f77903f. It should fix the problem. Just move your app.UseViteDevMiddleware() after the others middlewares.
