### ISSUE TITLE
After update to version 2.1.0, CSS files does not work in published version

### ISSUE THREAD

**Issue by Denis6902** [Eptagone/Vite.AspNetCore#120]
**Describe the bug**
When I make new css file and I want to link to this file in .cshtml file, it works in development version but not in published version

**To Reproduce**
1. Download and run ViteNET.MVC example from this repo
2. Create new random .css file with some random content like `* {
    outline: 1px solid red;
}`
3. Add this file to rollupOptions in vite.config.ts to the input
4. Add link to this css file in _Layout.cshtml like `<link rel="stylesheet" vite-href="~/test.css" asp-append-version="true" />`

**Expected behavior**
CSS File should work in Development mode and also after publish (with dotnet) in published version

**Screenshots**
When running published version:
![image](https://github.com/Eptagone/Vite.AspNetCore/assets/62514727/08da3770-7c20-40c5-93c3-ff388ba6d5f9)

Publishing:
![image](https://github.com/Eptagone/Vite.AspNetCore/assets/62514727/5762650a-4d01-4157-b698-d104fb8bff54)

**Device (please complete the following information):**
 - OS: Windows 11
 - IDE/Editor: Visual Studio 2022

**Additional context**
- With version 2.0.0 works without any problems.
- Link to CSS file is missing when running published version
- I have .NET 8 with latest Vite

**Comment by Eptagone** [comment]
Hi, thanks for your report. You're right. I'll fix it in a moment.
