### ISSUE TITLE
.NET 9 SDK - hot reload and ViteTagHelperMonitor warning

### ISSUE THREAD

**Issue by seangwright** [Eptagone/Vite.AspNetCore#136]
**Describe the bug**
When running a .NET 8 app using the .NET 9 SDK, I see this error in the console.

```
Expected to find a static method 'ClearCache' or 'UpdateApplication' on type 'Vite.AspNetCore.ViteTagHelperMonitor, Vite.AspNetCore, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null' but neither exists.
```

This appears after a hot-reload when running the app via `dotnet watch`

**To Reproduce**
1. Add this library to an ASPNET Core app
2. Install the .NET 9 SDK
3. Run the app with `dotnet watch`
4. Perform a code update that would trigger a hot reload in a `.cshtml` file
5. See the warning in the console

**Expected behavior**
No warning

**Screenshots**
n/a

**Device (please complete the following information):**
 - OS: macos
 - IDE/Editor VS Code w/ C# DeKit, .NET 9 SDK

**Additional context**
I found this article <https://learn.microsoft.com/en-us/visualstudio/debugger/hot-reload-metadataupdatehandler?view=vs-2022#add-the-metadataupdatehandler> and I think it applies to this file <https://github.com/Eptagone/Vite.AspNetCore/blob/main/src/Vite.AspNetCore/Services/ViteTagHelperMonitor.cs>

**Comment by phillip-haydon** [comment]
@Eptagone i just ran into this issue and see its been fixed, but 2.3 was released on the 11th of november and this was fixed on the 18th. Is there any plan to release the fix? Thanks.

**Comment by Eptagone** [comment]
Hi @phillip-haydon, sorry for the delay. Yes, I had planned to published it along other changes, however this last one may take longer than expected.
But that's okay, I think I'll skip them for now and publish a new version.

**Comment by phillip-haydon** [comment]
Thank you! And thanks for creating an awesome package.

**Comment by Gildedter** [comment]
is it normal that my debug session restarts on vs2022? I have `Hot Reload on File Save` switched on, while also having `options.Server.AutoRun = true;` and `app.UseViteDevelopmentServer(true);`
