### ISSUE TITLE
Slow page load time

### ISSUE THREAD

**Issue by jackkjhsu** [Eptagone/Vite.AspNetCore#15]
Hi Quetzal,

I've set up an existing MVC project with this Vite.AspNetCore middle. Everything seems to work (release build with bundled assets and Vite dev server running along side Kestrel) with minimal changes in the vite.config.ts file. However, the only issue I have with the Vite set up is while running in dev mode, whenever the page (view) loads or an ajax request is made to the controller endpoint through javascript, it seems to take a few seconds for the requests to complete. From what I can tell, this issue seems to be caused by Vite proxy server serving up the asset files (css, js, images etc). If I remove the `app.UseViteDevMiddleware();` line from Program.cs, everything loads up fast as expected but then the js and css files are bundled. Not exactly what I want for dev environment.

Is there anything I can do to make the Vite proxy serve up requests faster? Or alternatively any way I can disable the Vite dev server while retaining the unminified asset files in dev mode and bundled asset files in release mode?

Thanks

**Comment by Eptagone** [comment]
Hi @jackkjhsu
It's true that with the middleware enabled, the requests may take a little longer but it rarely takes seconds. At least in my local tests, it only takes a few milliseconds more. However, I'm going to review it, I think I have an idea to minimize the problem.

In the meantime, you could disable the middleware as you say. The [minification can be disabled](https://vitejs.dev/config/build-options.html#build-minify) according with the vite website. But I think it would help you better if you [enable the sourcemap files](https://vitejs.dev/config/build-options.html#build-sourcemap) so you can debug and see your original files in the inspector. There's a [watch option](https://vitejs.dev/config/build-options.html#build-watch) too.

**Comment by Eptagone** [comment]
Hello. I make a fix with commit 95c512cc236833cde36aedda5ebee7922f77903f. Just move your `app.UseViteDevMiddleware` after other middlewares.
I'll upload the setting to NuGet in a few moments.

**Comment by jackkjhsu** [comment]
Hi Quetzal,

Thanks a lot for the quick answer and the fix. I've moved the `app.UseViteDevMiddleware` call to the bottom just before `app.Run();`. The page load is still pretty slow because of all the asset file loading, but the ajax requests now works as expected, taking only milliseconds to complete as opposed to more than 2 seconds before. It'd be great if the page load issue can be addressed with the middleware fix as well. I'm hoping this is not an underlying Vite issue. In the meantime, I'm going to look into disabling minification in dev mode as you suggested above.

Here's a recording of the slow page load in action:
![datagrid_demo](https://user-images.githubusercontent.com/5721138/235680413-f408ea2c-9a14-4689-982c-8e94f97d5a85.gif)

**Comment by Eptagone** [comment]
Hi @jackkjhsu 

It's normal that the middleware is a bit slower than using the urls directly to the vite server. But I'm surprised it takes so long. Don't you have too many entrypoints? Are you using the latest version of Vite? Are you using an old computer?

Have you tried using the vite development server without the middleware? To measure response time.

**Comment by jackkjhsu** [comment]
Hi Quetzal,

Thanks again for responding.
About entry points, I have the following:
From \Views\Shared\_Layout.cshtml:
```
    <link rel="stylesheet" vite-href="~/main.ts" />
    <script type="module" vite-src="~/main.ts" asp-append-version="true"></script>
```
From \Views\Home\Index.cshtml:
```
@section Header {
    <link rel="stylesheet" vite-href="~/home.ts" />
    <script type="module" vite-src="~/home.ts" asp-append-version="true"></script>
}
```
Vite version: Updated to the latest v4.3.4, page load time still slow, no improvements.
My computer old? It's only a few months old. 11th Gen Intel Core i7-1165G7 @ 2.80GHz with 40GB RAM.
I haven't tried using Vite on its own without the middleware.

Also one note. Even with the ViteNET.MVC project from one of the examples, it still takes more than 6 seconds to load up the home page.
![image](https://user-images.githubusercontent.com/5721138/235701091-aa088706-41a5-4415-9d66-87b9c6bd4f90.png)

**Comment by Eptagone** [comment]
Hmm. When I test the ViteNET.MVC project on my local, I get these results.

<img width="721" alt="image" src="https://user-images.githubusercontent.com/23562885/235829497-e157fa2d-3f60-4534-9cd5-e0556ca479d7.png">

Even if I recharge several times, the time doesn't reach a second. I wonder what is affecting you. Mmm.
What node version are you using? is it the latest (v18 LTS)?

**Comment by jackkjhsu** [comment]
Hi Quetzal,

Good call with the NodeJs version. I just updated it to v20.0.0 from v16.17.0. The difference in load time performance is night and day! It's now running in the 500ms to 700ms range as opposed to 8s to 10s before. 
Thanks again for all your help.
![image](https://user-images.githubusercontent.com/5721138/235940665-b15ffbab-c86e-4b17-a5c7-af26d58648ea.png)

**Comment by Eptagone** [comment]
Perfect. You're welcome.
Then, I'm going to close this issue.
