### ISSUE TITLE
Blazor WASM Support

### ISSUE THREAD

**Issue by schwartzmj** [Eptagone/Vite.AspNetCore#19]
This package is great. I've used it within a Razor Pages app and it was very straightforward to use.

I apologize if this is a dumb question, but is it possible to use this within a Blazor WASM Hosted app? I've tested a bit and it seems like Server Side Blazor is the only Blazor type supported?

Thank you!

**Comment by Eptagone** [comment]
Hi, unfortunately in Blazor WASM there are no middlewares, so the library cannot be supported.
But I think it could work with Blazor United, included in the upcoming NET 8.
