### ISSUE TITLE
Does this support HMR

### ISSUE THREAD

**Issue by runxc1** [Eptagone/Vite.AspNetCore#28]
So I'm looking at using this with a vue.js project but when I tested the examples any changes that I made to the typescript files refreshes the entire page.   I'm curious if this has been tested with HMR or if that would work more seemless when using vue?

**Comment by Eptagone** [comment]
Hi @runxc1. The project hasn't been tested with all the features of Vite but there shouldn't be a problem. The premise of this project is proxy/redirect requests to the Vite Development Server, so you don't have to set up double paths. And also, it makes easier to retrieve data from the `manifest.json` file for your script and link tags.

So, you're still free to configure your Vite and/or AspNetCore environment as you want to suit your needs.

If you think the project is preventing or blocking any settings, feel free to report it for review, thanks.

**Comment by Eptagone** [comment]
Hi, the HMR issue was finally fixed with the f5941b06b1dc4429bb9feb3da5c997ab1e395d71 commit. More info: https://github.com/Eptagone/Vite.AspNetCore/issues/52
