### ISSUE TITLE
It would be nice if possible support for .net 3.1

### ISSUE THREAD

**Issue by dorathoto** [Eptagone/Vite.AspNetCore#42]
It would be nice if possible support for .net 3.1

due to the size of legacy projects.

**Comment by Eptagone** [comment]
Hi, mmm. I'm not sure, because net 3.1 is out of support.

**Comment by Eptagone** [comment]
Hi, I'm closing this one. There won't be net 3.1 support but if you still need it. You can make a copy of this project and modify it to support net 3.1
