### ISSUE TITLE
Version 1.9 breaks relative PackageDirectory

### ISSUE THREAD

**Issue by Webcoda** [Eptagone/Vite.AspNetCore#44]
You can use [my repo](https://github.com/Webcoda/test-viteaspnetcore18) to test

1. Change the version of Vite.AspNetCore to 1.9.0 from 1.8.0 on UmbracoCMS\UmbracoCMS.csproj
2. Run using `dotnet run`

you'll see this no package.json found error
![image](https://github.com/Eptagone/Vite.AspNetCore/assets/4045007/85f24f7d-36d7-4cb8-ad3a-680ad63ca50a)

I believe below change breaks it

![image](https://github.com/Eptagone/Vite.AspNetCore/assets/4045007/f6d08bd1-7884-4af8-ba08-bd143ba62fb0)

**Comment by Eptagone** [comment]
Hello. Yes, I see that there's a problem there. I'll see what i can do.
But I have a question. Why do I have your assets outside the project folder?

**Comment by Eptagone** [comment]
Hello. Yes, I see that there's a problem there. I'll see what i can do.
But I have a question. Why do you have your assets outside the project folder?

**Comment by Webcoda** [comment]
I just need to separate the backend and front end folders. although the build output will be in the project folder

**Comment by jdryden572** [comment]
Hi @Eptagone and @Webcoda, I also hit this issue upon upgrade because I'm keeping my Vite client app within a subfolder of my AspNetCore project. I hope you don't mind I opened a PR to address this.

**Comment by Eptagone** [comment]
Hi @jdryden572. It's no problem, thank you very much for fixing it. :)
