### ISSUE TITLE
ViteTagHelper cannot find chunk on Windows when not using ViteOptions.Base

### ISSUE THREAD

**Issue by jdryden572** [Eptagone/Vite.AspNetCore#46]
Since #43 was merged, `ViteTagHelper` attempts to normalize script references to use the system's path separator. So with a script tag like this one:
```html
<script type="module' vite-src="~/src/main.js"></script>
```
the `ViteTagHelper` normalizes the script reference to `src\main.js` when running on Windows, and then attempts to look up a chunk by that string. 

If the app is not overriding `ViteOptions.Base`, then the chunk dictionary in `ViteManifest` is not updated to normalize the keys to use the same Windows path separator, so the entrypoint for `src/main.js` remains as-is and the key is stored in the dictionary with the forward slash. This means production builds on Windows cannot resolve assets from the manifest if they have a path separator in them.

I'd like to voluteer to fix this issue, if that's alright. I think it may make most sense to always use Unix-style path separators for the chunks, since that is what Vite will produce in the assets manifest regardless of platform. It also matches how `script` and `link` tags will be referencing the assets since URLs use the forward slash in that context too.

**Comment by Eptagone** [comment]
Fixed with [v1.9.3](https://github.com/Eptagone/Vite.AspNetCore/releases/tag/v1.9.3). Thanks
