### ISSUE TITLE
Issue with Vite.Base Usage in Different Environments

### ISSUE THREAD

**Issue by frisksitron** [Eptagone/Vite.AspNetCore#48]
There's a discrepancy in the way `Vite.Base` behaves between development and production environments, requiring separate script tags for each.

With `Vite.Base` set to "build":

In the development environment, the following script tag is effective:
`<script type="module" vite-src="~/main.ts"></script>`

However, for production, we need:
`<script type="module" vite-src="~/build/main.ts"></script>`

This inconsistency arises because the chunk key (`main.ts`) is combined with the `Vite.Base` directory (`build`) when constructing `ViteManifest`, which results in chunk keys that doesn't match with the Vite dev server.

I created a branch which removes the `Vite.Base` directory from the chunk key: https://github.com/frisksitron/Vite.AspNetCore/tree/bugfix/wrong-manifest-key

This fixed the problem for me, but I don't know if this is the right approach. An alternate solution would be to for the Vite dev server to take `Vite.Base` into consideration when serving assets.

**Comment by Eptagone** [comment]
Hi. Did you try this for both environments?
```CSHTML
<script type="module" vite-src="~/build/main.ts"></script>
```
I thought it works. 🤔

**Comment by frisksitron** [comment]
You're right. However, you do need to add `base` to the `vite.config.ts` file for it to function properly. I overlooked that.

```typescript
const config: UserConfig = {
  base: appsettings.Vite.Base,
  ...
}
```

Perhaps this should be mentioned in the README?

**Comment by Eptagone** [comment]
Mmm, maybe we should use the Wiki tab for all those details.

**Comment by Eptagone** [comment]
Hi. I added this information to the new [Wiki](https://github.com/Eptagone/Vite.AspNetCore/wiki). So I'm going to close this topic.
