### ISSUE TITLE
Prevent Flash of unstyled content (FOUC)

### ISSUE THREAD

**Issue by seangwright** [Eptagone/Vite.AspNetCore#50]
When I run in "development" mode, the middleware makes a request back to the Vite server and the JS file injects the `<style>` element into the DOM.

This results in the page rendering unstyled and then all the styles flash in. This happens for _every_ navigation, which is kinda painful.

Is there any way to fix this? It doesn't look like Vite can serve CSS directly.

I assume one solution is run [Vite in build "watch" mode](https://vitejs.dev/config/build-options.html#build-watch) and link directly to the build assets, but defeats the purpose of Vite 😥

**Comment by Eptagone** [comment]
Hi @seangwright. Yes, there is a way.
Use your style file (ex: `main.css`) as an entry point instead of importing it from your `js/ts` file (ex: `main.ts`). This way the browser will load the styles directly instead of loading them from the script.

```TypeScript
// vite.config.ts
const config: UserConfig = {
    build: {
        rollupOptions: {
            input: [
                'Assets/main.ts',
                'Assets/style.scss'
            ],
        }
    }
}
```
```CSHTML
@* _layout.cshtml *@
<link rel="stylesheet" vite-href="~/style.scss" />
```

**Comment by seangwright** [comment]
Thanks, that worked!
