### ISSUE TITLE
Using modulepreload causes warning for ES modules

### ISSUE THREAD

**Issue by seangwright** [Eptagone/Vite.AspNetCore#51]
I have the following in my `<head>`

```html
<link rel="preload" vite-href="~/styles/style.scss" as="style" />
<link rel="modulepreload" vite-href="~/js/main.js" as="script" />

<!-- ... other stuff -->

<link rel="stylesheet" vite-href="~/styles/style.scss" />
```

and at the end of my `<body>`

```html
<script type="module" vite-src="~/js/main.js"></script>
```

These preload keywords are used to inform the browser [to start downloading an asset even before it is used](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/modulepreload).

When I use these with a `.js` module using `vite-href` I get the following warning

```
warn: Vite.AspNetCore.TagHelpers.ViteTagHelper[0]
The entry 'js/main.js' doesn't have CSS chunks
```

My thought is that the logic in the [ViteTagHelper](https://github.com/Eptagone/Vite.AspNetCore/blob/6f0deb002f64f2098ce404d8d26d448f1659b16a/src/Vite.AspNetCore/TagHelpers/ViteTagHelper.cs) needs to be expanded to handle these scenarios or it needs to be less strict about what it's validating.

**Comment by Eptagone** [comment]
Hi, sorry for the delay.
I added a validation for link tags with 6e28af55ad10127553bae71a89f08b8f2855c536. For links without `rel="stylesheet"`, the script url will be used instead of CSS url.
