### ISSUE TITLE
ViteManifest incorrectly adding ViteOptions.Base to chunk key

### ISSUE THREAD

**Issue by Kenshinofkin** [Eptagone/Vite.AspNetCore#60]
I have setup vitejs build outDir to output to `../wwwroot/client`. In my appsettings.json, I have the following configuration:

`
"Vite": {
    "Manifest": "assets.manifest.json",
    "Base": "client",
    "PackageDirectory": "Client"
  }
`

In one of my MVC views I am using `<script type="module" vite-src="~/src/main.tsx"></script>`. When running vitejs dev server main.tsx is served. And works fine. But when I publish, I get an error 

> "src/main.tsx" was not found in Vite manifest file (check /Views/Home/Index.cshtml)

And a warning

> The chunk 'src/main.tsx' was not found

I pulled Vite.AspNetCore into my project and found that in ViteManifest.cs, when the chunks are being created from the vite manifest, ViteOptions.Base is added to the chunk key. The tag helper is than unable to find `~/src/main.tsx` because the chunks now contain an entry for `client/src/main.tsx` and not `src/main.tsx`.

**Comment by Kenshinofkin** [comment]
Working

**Comment by Eptagone** [comment]
Hi, if you set `client` as base, then your entrypoint is `client/src/main.tsx`, not `src/main.tsx`

**Comment by Eptagone** [comment]
Hi @Kenshinofkin. I'll close this issue for inactivity.
If you still having problems configuring a base path, you can check on the [Wiki](https://github.com/Eptagone/Vite.AspNetCore.wiki.git). If that doesn't work for you, feel free to open a new issue or discussion.
