### ISSUE TITLE
Anyone having issues with Vite server not starting under Visual Studio 2022 17.8.0 Preview 4

### ISSUE THREAD

**Issue by panterlo** [Eptagone/Vite.AspNetCore#61]
Anyone having a similar issue not getting the Vite server to auto-start under Visual Studio 2022 17.8.0 Preview 4 as seen below ? If I run it from the command line it operates just fine.

![2023-10-20_15-57-24](https://github.com/Eptagone/Vite.AspNetCore/assets/320204/46b38ee8-7308-4149-ba10-6e305ed43b83)

**Comment by Eptagone** [comment]
Does this issue only occur with the Preview version?
I have tried it in my local but without the preview version and it works.

**Comment by Eptagone** [comment]
I'm closing this as completed. If the problem persists and you have mor information, feel free to open a new issue with all details you have.
