### ISSUE TITLE
Vite 5 manifest.json changes

### ISSUE THREAD

**Issue by ameyer117** [Eptagone/Vite.AspNetCore#66]
Hello & thank you for creating this library!

Just wanted to say that you might want to put a note somewhere guiding users what to do with Vite 5...

They changed where the manifest.json file gets placed in production builds to be `dist/.vite/manifest.json` instead of just `dist/manifest.json`. [More details here](https://vitejs.dev/guide/migration.html#manifest-files-are-now-generated-in-vite-directory-by-default)

**Comment by Eptagone** [comment]
Hello, that's exactly what i'm doing right now. I'll commit it in a few minutes.

**Comment by Eptagone** [comment]
Okey, the changes are ready with 34ef16ce3ed02c5c818ead3ee5c3932001f5e1fe

**Comment by Eptagone** [comment]
Hello. I'll close this as completed.

Also, from what I see, we will have to add this to the project file:
```xml
<!-- AspNetProject.csproj -->
<ItemGroup>
    <Content Include="wwwroot\.vite\manifest.json" />
</ItemGroup>
```

The Vite manifest with the new name is not copied when publishing. I suppose it's because of the dot in the new name: `.vite/manifest.json`.
