### ISSUE TITLE
Can't find the @@Vite/Client,

### ISSUE THREAD

**Issue by LittleWhiteLoti** [Eptagone/Vite.AspNetCore#68]
![image](https://github.com/Eptagone/Vite.AspNetCore/assets/61956115/eff9e94e-624f-404b-ba0b-4baaeec8dae4)

I started up the ViteNet Razor pages from the github repo. Any clue what might be happening. I do have vite 5.03 installed.

**Comment by Eptagone** [comment]
Hi, did you try to reload the page? That can happen if the Vite Dev Server is not ready yet.

**Comment by LittleWhiteLoti** [comment]
@Eptagone Thanks for getting back so quickly.

**Comment by Eptagone** [comment]
Mmm, can you access to `https://localhost:5173/@vite/client ` in the browser?
Did you try to run `npm ci`? to clean install que npm packages

**Comment by LittleWhiteLoti** [comment]
I did run npm ci and it just downloaded a few packages. One which was vulnerable by the way.

In the ViteNet.MVC example project whenever I try to visit https://localhost:5173/@vite/client

Firefox
![image](https://github.com/Eptagone/Vite.AspNetCore/assets/61956115/06e7e4a9-2267-46b9-98dd-60aab0b9718d)

Chrome
![image](https://github.com/Eptagone/Vite.AspNetCore/assets/61956115/435f739d-7457-4bde-9ef0-54e821668636)

Edge
![image](https://github.com/Eptagone/Vite.AspNetCore/assets/61956115/9efd818c-f1c0-4779-98a0-1ed799e6cbd1)

**Comment by Eptagone** [comment]
Hi. It's true that there were vulnerable NPM packages. I just updated them.
Please let me know if with those changes you can now run the Razor pages example.

Regarding the SSL error in Firefox, I don't know if regenerating the self-signed certificate could help.
https://learn.microsoft.com/en-us/dotnet/core/additional-tools/self-signed-certificates-guide

**Comment by LittleWhiteLoti** [comment]
Windows 10 with Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.8.2

Tell me if I'm doing something wrong. These are the steps I'm doing.
1. Clone repo
2. Build Vite.RazorPages project from examples
3. Run project

**Comment by Eptagone** [comment]
Hi. I just tested it in my machine, and it seems to work fine.
I'm using:
- Google Chrome (Official Release) v120.0.6099.129
- Windows 11 23H2
- Visual Studio 2022 v17.8.3
<img width="960" alt="image" src="https://github.com/Eptagone/Vite.AspNetCore/assets/23562885/8ac13396-2eb9-4882-afaa-e95912b487c2">

You could try to [trust the ASP.NET certificate](https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-8.0&tabs=visual-studio%2Clinux-ubuntu#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos) again.

**Comment by frisksitron** [comment]
This might not be related to your issue @LittleWhiteLoti, but ViteOptionsExtensions.GetViteDevServerUrl does not take ViteOptions.Base into account. So if we configure a subfolder for vite assets, the @vite/client won't load.

**Comment by LittleWhiteLoti** [comment]
@frisksitron did you get it to work? Can you provide an example project that I might look at? I'm trying to get it to work with Vue 3 and vite.

**Comment by Deepfreezed** [comment]
@LittleWhiteLoti basic sample provided works. Vue should also work based on that because everything is JS.

If you are cloning the sample. below worked for me:

npm install
npm build
npm dev
Run ASP.NET (hit F5 on browser if is doesn't load first time)

**Comment by LittleWhiteLoti** [comment]
@Deepfreezed thanks I will test it later

**Comment by LittleWhiteLoti** [comment]
Okay I finally got it to work for the following steps.

Use Visual Studio not visual studio code.
1. Clone repo https://github.com/Eptagone/Vite.AspNetCore.git
2. Open the solution from examples ViteNET.sln
3. Set ViteNET.RazorPages as the default startup project if it is not already setup
4. Open powershell and navigate to the examples/ViteNET.RazorPages
5. run npm i
5. From Visual Studio build the project
6. start the project from Visual Studio's play button
7. Wait for it to load once in the browser, then refresh it again to load everything
