### ISSUE TITLE
Vite.Server:UseFullDevUrl causes full page reload

### ISSUE THREAD

**Issue by cayroso** [Eptagone/Vite.AspNetCore#79]
**Describe the bug**
When the setting in the manifest is set to "**false**", it causes full page **reload**.
All the vuejs components get requested from the server.

But if the flag is set to "**true**", it works as expected.

**Comment by Eptagone** [comment]
Hi @cayroso. The flag `UseFullDevUrl` should always be `True` to make Vite works properly in most cases.
That's why that settings will be removed with the next release. Tag Helpers will always render the full dev server URL now.

**Comment by cayroso** [comment]
If that will be updated to that in the future, this ticket will not be relevant anymore.
I'm closing the ticket now, thanks!.
