### ISSUE TITLE
Hot Reload issues

### ISSUE THREAD

**Issue by panterlo** [Eptagone/Vite.AspNetCore#9]
Have you had any issues with hot reload stop working after pulling in the Vite.AspnetCore ? For some reason it stopped working for me and I am trying to find the reason why.

**Comment by Eptagone** [comment]
Hi panterlo. Could you provide more details? Is there any error in the console?

**Comment by panterlo** [comment]
I wonder if they maybe broke hot reload in Version 17.6.0 Preview 3.0 (again) and it's not related to Vite.AspNetCore. If you modify a cshtml page and save it the bottom footer would say "No code changes were found" but hitting the hot reload button manually it would of course work. So it seems like it relates to an internal issue in Visual Studio.

Just created a plain new ASP.NET Core Web App project and indeed the hot reload seems to be broke.

**Comment by panterlo** [comment]
Further , connecting to the web socket for hot reload you can see that modifying the code would trigger hot reload but for some reason the razor view hotreload has become broken in Preview 3.0 of VS 17.6.0.
![image](https://user-images.githubusercontent.com/320204/232280440-43327f63-ce8e-454f-a9c5-615d43dafcb3.png)

**Comment by Eptagone** [comment]
I see. Then I'll close this issue.
We'll have to wait for them to fix it.
